/////////////////////////////////////////////////////////////////////////////
// messages namespace support (see _messages.c generated by YResourc.exe)
#ifndef MESSAGES_NAMESPACE_DEFINED
#define MESSAGES_NAMESPACE_DEFINED

extern
#ifdef  __cplusplus
"C"
#endif//__cplusplus
struct { const char* szDesc; const char* szType; unsigned nID; void* handle;  unsigned nReserved; const char* azReserved; } g_messages_namespace[];

#endif//MESSAGES_NAMESPACE_DEFINED
