/////////////////////////////////////////////////////////////////////////////
// resource namespace support (see resource.c generated by YResourc.exe)
#ifndef RESOURCES_NAMESPACE_DEFINED
#define RESOURCES_NAMESPACE_DEFINED

extern
#ifdef  __cplusplus
"C"
#endif//__cplusplus
struct { const char* szDesc; const char* szType; unsigned nID; void* handle;  unsigned nReserved; const char* azReserved; } g_resources_namespace[];

#endif//RESOURCES_NAMESPACE_DEFINED
